FROM node:18.16.1

WORKDIR /usr/src/app

# Install app dependencies
COPY node_modules .
COPY public .
COPY ecosystem.config.js .

RUN npm install pm2 -g

CMD [ "pm2-runtime", "start", "ecosystem.config.js" ]
